### ISSUE TITLE
Error: INFO: Could not find files for the given pattern(s)

### ISSUE THREAD

**Issue by JD-2006** [StelaBou/HyperReenact#2]
On Windows 10 x64, after creating conda env and activating, running "python run_inference.py --source_path ./inference_examples/source.png --target_path ./inference_examples/target_video_1.mp4 --output_path ./results --save_video" I get error:

INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "I:/AI_and_DeepFake/Speech_Models/HyperReenact/run_inference.py", line 20, in <module>
    from libs.models.encoders.psp_encoders import Encoder4Editing
  File "I:\AI_and_DeepFake\Speech_Models\HyperReenact\libs\models\encoders\psp_encoders.py", line 9, in <module>
    from libs.models.gan.StyleGAN2.model import EqualLinear, ScaledLeakyReLU, EqualConv2d
  File "I:\AI_and_DeepFake\Speech_Models\HyperReenact\libs\models\gan\StyleGAN2\model.py", line 8, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "I:\AI_and_DeepFake\Speech_Models\HyperReenact\libs\models\gan\StyleGAN2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "I:\AI_and_DeepFake\Speech_Models\HyperReenact\libs\models\gan\StyleGAN2\op\fused_act.py", line 10, in <module>
    fused = load(
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\site-packages\torch\utils\cpp_extension.py", line 969, in load
    return _jit_compile(
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\site-packages\torch\utils\cpp_extension.py", line 1176, in _jit_compile
    _write_ninja_file_and_build_library(
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\site-packages\torch\utils\cpp_extension.py", line 1268, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\site-packages\torch\utils\cpp_extension.py", line 1646, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\site-packages\torch\utils\cpp_extension.py", line 1757, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "I:\AI_and_DeepFake\Speech_Models\hyperreenact_env\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

All example files seem to be where they are supposed to be.

**Comment by StelaBou** [comment]
This seems to be an issue with the StyleGAN2 dependencies. Unfortunately I haven't tested the code on Windows and I have never encountered a similar issue.
Could you please verify your Python, Pytorch and Cuda versions?
There is one similar issue on Windows [here](https://github.com/rosinality/stylegan2-pytorch/issues/216).
