### ISSUE TITLE
Conflict of toolkit11.0

### ISSUE THREAD

**Issue by YacratesWyh** [StelaBou/HyperReenact#5]
https://github.com/pytorch/pytorch/issues/51080
I think we have to get on to 11.1

**Comment by YacratesWyh** [comment]
Still in 11.0
Run reenactment for 101 images. Save results into ./results
  0%|                                                                                                                                                                                                                                                    | 0/101 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "run_inference.py", line 298, in <module>
    main()
  File "run_inference.py", line 293, in main
    inference.run_reenactment()
  File "run_inference.py", line 222, in run_reenactment
    reenacted_image = self.forward_model(source_image, target_image, source_code)
  File "run_inference.py", line 145, in forward_model
    pose_hat, f_pose = self.get_pose_embeddings(target_img)
  File "run_inference.py", line 133, in get_pose_embeddings
    image_prepro_, error_flag = self.posedata.get_image_tensor(image_pose[k])
  File "/home/admin188/AI/reenactment/HyperReenact/libs/DECA/decalib/datasets/datasets.py", line 98, in get_image_tensor
    dst_image = kornia.warp_affine(image_tensor, theta[:,:2,:], dsize=(224, 224))
  File "/home/admin188/anaconda3/envs/hyperreenact_env/lib/python3.8/site-packages/kornia/geometry/transform/imgwarp.py", line 143, in warp_affine
    dst_norm_trans_src_norm: torch.Tensor = normalize_homography(
  File "/home/admin188/anaconda3/envs/hyperreenact_env/lib/python3.8/site-packages/kornia/geometry/warp/homography_warper.py", line 350, in normalize_homography
    src_pix_trans_src_norm = torch.inverse(src_norm_trans_src_pix)
RuntimeError: cusolver error: 7, when calling `cusolverDnCreate(handle)`

No idea what happened, maybe need to bypass something.

**Comment by YacratesWyh** [comment]
Fixed by 
1.upgrade kornia, torch torchvision to latest
2. replace kornia.warp_affine to kornia.geometry.transform
3. revise opencv writing from 'MP4V' to 'mp4v'
